[package]
name = "cykusz_rs"
version = "0.1.0"
authors = ["Rafal Mielniczuk <rafal.mielniczuk2@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "*"
spin = "*"
bitflags = "1.0"

[dependencies.lazy_static]
version = "*"
features = ["spin_no_std"]


