[build]
rustc = "../sysroot/cross/usr/local/bin/rustc"
target = "x86_64-unknown-cykusz"
rustflags = ["-C", "link-args=-no-pie", "-C", "link-args=-lgcc_s", "-Z", "threads=8"]

[env]
CC = { value = "../sysroot/cross/usr/bin/x86_64-cykusz-gcc", relative = true }
AR = { value = "../sysroot/cross/usr/bin/x86_64-cykusz-ar", relative = true }

[target.x86_64-unknown-cykusz]
linker = "../sysroot/cross/usr/bin/x86_64-cykusz-gcc"

[patch.crates-io]
libc = { git = "https://github.com/rafalmiel/libc.git", branch = "cykusz" }
