[package]
authors = ["Rafal Mielniczuk <rafal.mielniczuk2@gmail.com>"]
edition = "2018"
name = "cykusz_rs"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "*"
raw-cpuid = "*"
spin = "*"
bit_field = "*"
intrusive-collections = "*"

[dependencies.linked_list_allocator]
version = "*"
features = ["alloc_ref"]

[dependencies.syscall-defs]
path = "../syscall-defs"

[dependencies.acpica]
path = "../acpica"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "*"
