[package]
authors = ["Rafal Mielniczuk <rafal.mielniczuk2@gmail.com>"]
edition = "2018"
name = "cykusz_rs"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "*"
raw-cpuid = "*"
spin = "*"
bit_field = "*"
intrusive-collections = "*"
paste = "*"
mmio = "*"
lru = "*"
downcast-rs = { version = "1.2.0", default-features = false }

[dependencies.chrono]
default-features = false
version = "*"

[dependencies.linked_list_allocator]
version = "*"

[dependencies.syscall-defs]
path = "../syscall-defs"

[dependencies.acpica]
path = "../acpica"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "*"
