[package]
name = "userspace"
version = "0.1.0"
edition = "2021"

[dependencies.chrono]
default-features = false
version = "*"

[dependencies.syscall-defs]
path = "../syscall-defs"

[dependencies.syscall-user]
path = "../syscall-user"
